### ISSUE TITLE
키워드 추천 페이지 UI

### ISSUE THREAD

**Issue by donggyunhuh** [donggyunhuh/TeamProjectFlower_Sourcecode#73]
피그마를 사용해서 제작중입니다.

**Comment by d0kyoung** [comment]
피그마를 사용해서 꽃 추천페이지의 UI를 제작했습니다. 
키워드 선택 페이지, 꽃 추천 로딩 페이지, 추천 결과페이지입니다. 
[https://www.figma.com/file/tWJizqxXmYMFLOvOuNIm2K/dohwada?type=whiteboard&node-id=0%3A1&t=UJBhMYBsjIOovWyX-1](url)
