### ISSUE TITLE
주문서 - 매장 매칭 기능

### ISSUE THREAD

**Issue by d0kyoung** [donggyunhuh/TeamProjectFlower_Sourcecode#85]

**Comment by d0kyoung** [comment]
주문서를 실시간으로 매장 사장님에게 전송하기 위한 WebSocket의 구성이 필요함. WebSocketConfig 클래스를 사용하여 구성할 것

**Comment by donggyunhuh** [comment]
IntelliJ  SpringWebSocket 설치

**Comment by d0kyoung** [comment]
로컬 서버에서 돌리기 때문에 매장 별 웹사이트를 가동하는 방식으로 변경해서 웹소켓을 삭제하고 1:1 주문 방식으로 변경함
